application: boardgame-night
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:

#require user to login to view profile page
- url: /profile
  script: main.app
  login: required
  auth_fail_action: redirect


- url: /static
  static_dir: static

- url: .*
  script: main.app

